separate_dataset: true

flag: test

seq_len: 0

label_len: 0

features: S

target: target

scale: false

batch_size: 1

pad: false

num_workers: 10

pred_style: ensemble

ensemble_config:
  max_fraction: 0.4
  num_ensembles: 4
  method: mean